In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.preprocessing import LabelEncoder
import pickle

In [2]:
df = pd.read_csv(r"C:\Users\mutyam bhargav reddy\Downloads\car_resale\autos.csv", header=0, sep=',', encoding='Latin1',)

In [3]:
df

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450Â€_VB,privat,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÃœV_3.2018,privat,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [4]:
df.head

<bound method NDFrame.head of                 dateCrawled  \
0       2016-03-24 11:52:17
1       2016-03-24 10:58:45
2       2016-03-14 12:52:21
3       2016-03-17 16:54:04
4       2016-03-31 17:25:20
5       2016-04-04 17:36:23
6       2016-04-01 20:48:51
7       2016-03-21 18:54:38
8       2016-04-04 23:42:13
9       2016-03-17 10:53:50
10      2016-03-26 19:54:18
11      2016-04-07 10:06:22
12      2016-03-15 22:49:09
13      2016-03-21 21:37:40
14      2016-03-21 12:57:01
15      2016-03-11 21:39:15
16      2016-04-01 12:46:46
17      2016-03-20 10:25:19
18      2016-03-23 15:48:05
19      2016-04-01 22:55:47
20      2016-04-01 19:56:48
21      2016-03-27 11:38:00
22      2016-03-23 14:52:51
23      2016-03-12 19:43:07
24      2016-03-13 20:40:49
25      2016-03-18 21:44:09
26      2016-03-10 19:38:18
27      2016-03-07 12:51:23
28      2016-03-09 11:56:38
29      2016-03-08 19:55:19
...                     ...
371498  2016-03-11 15:50:38
371499  2016-03-08 13:52:00
371500  2016-03-21 23:40:49
371501  2016-03-26 18:36:54
371502  2016-04-01 12:59:21
371503  2016-04-01 01:55:58
371504  2016-03-07 17:06:35
371505  2016-04-03 19:56:57
371506  2016-03-20 18:47:59
371507  2016-03-16 17:06:19
371508  2016-04-02 16:43:27
371509  2016-03-11 23:40:32
371510  2016-03-06 21:11:23
371511  2016-03-31 18:50:37
371512  2016-03-25 18:48:06
371513  2016-03-21 15:36:22
371514  2016-04-04 11:45:16
371515  2016-03-09 11:36:55
371516  2016-04-04 09:57:12
371517  2016-03-28 13:48:07
371518  2016-04-02 20:37:03
371519  2016-03-09 13:37:43
371520  2016-03-19 19:53:49
371521  2016-03-27 20:36:20
371522  2016-03-21 09:50:58
371523  2016-03-14 17:48:27
371524  2016-03-05 19:56:21
371525  2016-03-19 18:57:12
371526  2016-03-20 19:41:08
371527  2016-03-07 19:39:19

                                                     name  seller offerType  \
0                                              Golf_3_1.6  privat   Angebot
1                                    A5_Sportback_2.7_Tdi  privat   Angebot
2                          Jeep_Grand_Cherokee_"Overland"  privat   Angebot
3                                      GOLF_4_1_4__3TÃœRER  privat   Angebot
4                          Skoda_Fabia_1.4_TDI_PD_Classic  privat   Angebot
5       BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...  privat   Angebot
6                             Peugeot_206_CC_110_Platinum  privat   Angebot
7                            VW_Derby_Bj_80__Scheunenfund  privat   Angebot
8                    Ford_C___Max_Titanium_1_0_L_EcoBoost  privat   Angebot
9       VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...  privat   Angebot
10                                      Mazda_3_1.6_Sport  privat   Angebot
11          Volkswagen_Passat_Variant_2.0_TDI_Comfortline  privat   Angebot
12                      VW_Passat_Facelift_35i__"7Sitzer"  privat   Angebot
13                         VW_PASSAT_1.9_TDI_131_PS_LEDER  privat   Angebot
14      Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...  privat   Angebot
15                           KA_Lufthansa_Edition_450Â€_VB  privat   Angebot
16                                            Polo_6n_1_4  privat   Angebot
17                            Renault_Twingo_1.2_16V_Aut.  privat   Angebot
18                       Ford_C_MAX_2.0_TDCi_DPF_Titanium  privat   Angebot
19                      Mercedes_Benz_A_160_Classic_Klima  privat   Angebot
20                      Volkswagen_Scirocco_1.4_TSI_Sport  privat   Angebot
21      BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...  privat   Angebot
22                          Opel_Meriva_1.Hand_TÃœV_3.2018  privat   Angebot
23                                           Stadtflitzer  privat   Angebot
24                             MERCEDES_200E__TÃœV_04/2016  privat   Angebot
25                  BMW_530d_touring_Vollausstattung_NAVI  privat   Angebot
26                              Citroen_C4_Grand_Picasso.  privat   Angebot
27                         Honda_Civic_1.4_i_VTEC_Comfort  privat   Angebot
28                                   Volkswagen_T3_andere  privat   Angebot
29                                         Fiat_Punto_1.2  privat   Angebot
...                                                   ...     ...       ...
371498                            Opel_Vectra_Edition_100  privat   Angebot
371499  OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...  privat   Angebot
371500  Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...  privat   Angebot
371501                                   Chrysler_Voyager  privat   Angebot
371502                                  Audi_A4_Avant_1.8  privat   Angebot
371503                                   Subaru_Justy_1.3  privat   Angebot
371504                                       220_cdi_Benz  privat   Angebot
371505                   Opel_Astra_1.6_Caravan_Selection  privat   Angebot
371506  Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...  privat   Angebot
371507  Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...  privat   Angebot
371508                                     Opel_Astra_1.8  privat   Angebot
371509  LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...  privat   Angebot
371510  Mercedes_benz_e_klasse_avangarde_220_cdi_grune...  privat   Angebot
371511                           Audi_A3_1.8_T_Attraction  privat   Angebot
371512                 Mercedes_Benz_E_400_CDI_Avantgarde  privat   Angebot
371513                       Seat_Leon_1.9_TDI_4/5_Tueren  privat   Angebot
371514                 Renault_1_4_ltr.16_V_Megane_Cabrio  privat   Angebot
371515                              Skoda_Fabia_Kombi_1.4  privat   Angebot
371516                                Volkswagen_Lupo_1.0  privat   Angebot
371517                   Volkswagen_Golf_2.0_TDI_DPF_Team  privat   Angebot
371518                          Bmw_320_D_DPF_Touring_!!!  privat   Angebot
371519  Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll  privat   Angebot
371520                                       turbo_defekt  privat   Angebot
371521                 Opel_Zafira_1.6_Elegance_TÃœV_12/16  privat   Angebot
371522                                    Mitsubishi_Cold  privat   Angebot
371523                         Suche_t4___vito_ab_6_sitze  privat   Angebot
371524              Smart_smart_leistungssteigerung_100ps  privat   Angebot
371525                 Volkswagen_Multivan_T4_TDI_7DC_UY2  privat   Angebot
371526                             VW_Golf_Kombi_1_9l_TDI  privat   Angebot
371527       BMW_M135i_vollausgestattet_NP_52.720____Euro  privat   Angebot

        price   abtest vehicleType  yearOfRegistration    gearbox  powerPS  \
0         480     test         NaN                1993    manuell        0
1       18300     test       coupe                2011    manuell      190
2        9800     test         suv                2004  automatik      163
3        1500     test  kleinwagen                2001    manuell       75
4        3600     test  kleinwagen                2008    manuell       69
5         650     test   limousine                1995    manuell      102
6        2200     test      cabrio                2004    manuell      109
7           0     test   limousine                1980    manuell       50
8       14500  control         bus                2014    manuell      125
9         999     test  kleinwagen                1998    manuell      101
10       2000  control   limousine                2004    manuell      105
11       2799  control       kombi                2005    manuell      140
12        999  control       kombi                1995    manuell      115
13       2500  control       kombi                2004    manuell      131
14      17999  control         suv                2011    manuell      190
15        450     test  kleinwagen                1910        NaN        0
16        300     test         NaN                2016        NaN       60
17       1750  control  kleinwagen                2004  automatik       75
18       7550     test         bus                2007    manuell      136
19       1850     test         bus                2004    manuell      102
20      10400  control       coupe                2009    manuell      160
21       3699     test   limousine                2002  automatik      231
22       2900     test         NaN                2018    manuell       90
23        450     test  kleinwagen                1997    manuell       50
24        500     test   limousine                1990    manuell      118
25       2500  control       kombi                2002  automatik      193
26       5555  control         NaN                2017    manuell      125
27       6900     test   limousine                2008    manuell       99
28       1990     test         bus                1981    manuell       50
29        690     test  kleinwagen                2003    manuell       60
...       ...      ...         ...                 ...        ...      ...
371498    699  control   limousine                1999    manuell      101
371499    600  control  kleinwagen                1998    manuell       54
371500  20400     test   limousine                2014  automatik      150
371501   3900     test         bus                2003  automatik      174
371502   1600     test       kombi                1998    manuell      125
371503   1700  control  kleinwagen                1999    manuell       68
371504   2600  control         NaN                2005  automatik        0
371505    800     test       kombi                2000    manuell      101
371506   5900     test   limousine                2006    manuell      105
371507   5999     test       kombi                2005    manuell      140
371508   1400  control   limousine                2001    manuell      125
371509   1900     test         NaN                2000    manuell      110
371510   6500     test   limousine                2003  automatik      145
371511   1999  control   limousine                1997    manuell      150
371512   5000     test   limousine                2003  automatik      260
371513   4400  control   limousine                2008    manuell      105
371514    999  control      cabrio                2000    manuell       95
371515   1690     test       kombi                2004    manuell       55
371516   1490  control  kleinwagen                1998    manuell       50
371517   7900     test   limousine                2010    manuell      140
371518   3999     test       kombi                2005    manuell        3
371519   5250  control         NaN                2016  automatik      150
371520   3200  control   limousine                2004    manuell      225
371521   1150  control         bus                2000    manuell        0
371522      0  control         NaN                2005    manuell        0
371523   2200     test         NaN                2005        NaN        0
371524   1199     test      cabrio                2000  automatik      101
371525   9200     test         bus                1996    manuell      102
371526   3400     test       kombi                2002    manuell      100
371527  28990  control   limousine                2013    manuell      320

              model  kilometer  monthOfRegistration fuelType           brand  \
0              golf     150000                    0   benzin      volkswagen
1               NaN     125000                    5   diesel            audi
2             grand     125000                    8   diesel            jeep
3              golf     150000                    6   benzin      volkswagen
4             fabia      90000                    7   diesel           skoda
5               3er     150000                   10   benzin             bmw
6           2_reihe     150000                    8   benzin         peugeot
7            andere      40000                    7   benzin      volkswagen
8             c_max      30000                    8   benzin            ford
9              golf     150000                    0      NaN      volkswagen
10          3_reihe     150000                   12   benzin           mazda
11           passat     150000                   12   diesel      volkswagen
12           passat     150000                   11   benzin      volkswagen
13           passat     150000                    2      NaN      volkswagen
14           navara      70000                    3   diesel          nissan
15               ka       5000                    0   benzin            ford
16             polo     150000                    0   benzin      volkswagen
17           twingo     150000                    2   benzin         renault
18            c_max     150000                    6   diesel            ford
19         a_klasse     150000                    1   benzin   mercedes_benz
20         scirocco     100000                    4   benzin      volkswagen
21              5er     150000                    7   benzin             bmw
22           meriva     150000                    5   benzin            opel
23            arosa     150000                    5   benzin            seat
24           andere     150000                   10   benzin   mercedes_benz
25              5er     150000                    9   diesel             bmw
26               c4     125000                    4      NaN         citroen
27            civic      60000                   11   benzin           honda
28      transporter       5000                    1   benzin      volkswagen
29            punto     150000                    3   benzin            fiat
...             ...        ...                  ...      ...             ...
371498       vectra     150000                    3   benzin            opel
371499        corsa     150000                    1   benzin            opel
371500         golf      30000                    9   benzin      volkswagen
371501      voyager     150000                    7   benzin        chrysler
371502           a4     150000                    2   benzin            audi
371503        justy      70000                   11   benzin          subaru
371504     c_klasse     150000                    9      NaN   mercedes_benz
371505        astra     150000                   11   benzin            opel
371506         golf     150000                    9   diesel      volkswagen
371507           a4     150000                    4   diesel            audi
371508        astra     150000                    2   benzin            opel
371509          NaN     150000                    7      NaN      volkswagen
371510     e_klasse     150000                    3   diesel   mercedes_benz
371511           a3     150000                   12   benzin            audi
371512     e_klasse     150000                   12   diesel   mercedes_benz
371513         leon     150000                    7   diesel            seat
371514       megane     150000                    4   benzin         renault
371515        fabia     150000                    4   benzin           skoda
371516         lupo     150000                    9   benzin      volkswagen
371517         golf     150000                    7   diesel      volkswagen
371518          3er     150000                    5   diesel             bmw
371519          159     150000                   12      NaN      alfa_romeo
371520         leon     150000                    5   benzin            seat
371521       zafira     150000                    3   benzin            opel
371522         colt     150000                    7   benzin      mitsubishi
371523          NaN      20000                    1      NaN  sonstige_autos
371524       fortwo     125000                    3   benzin           smart
371525  transporter     150000                    3   diesel      volkswagen
371526         golf     150000                    6   diesel      volkswagen
371527      m_reihe      50000                    8   benzin             bmw

       notRepairedDamage          dateCreated  nrOfPictures  postalCode  \
0                    NaN  2016-03-24 00:00:00             0       70435
1                     ja  2016-03-24 00:00:00             0       66954
2                    NaN  2016-03-14 00:00:00             0       90480
3                   nein  2016-03-17 00:00:00             0       91074
4                   nein  2016-03-31 00:00:00             0       60437
5                     ja  2016-04-04 00:00:00             0       33775
6                   nein  2016-04-01 00:00:00             0       67112
7                   nein  2016-03-21 00:00:00             0       19348
8                    NaN  2016-04-04 00:00:00             0       94505
9                    NaN  2016-03-17 00:00:00             0       27472
10                  nein  2016-03-26 00:00:00             0       96224
11                    ja  2016-04-07 00:00:00             0       57290
12                   NaN  2016-03-15 00:00:00             0       37269
13                  nein  2016-03-21 00:00:00             0       90762
14                  nein  2016-03-21 00:00:00             0        4177
15                   NaN  2016-03-11 00:00:00             0       24148
16                   NaN  2016-04-01 00:00:00             0       38871
17                  nein  2016-03-20 00:00:00             0       65599
18                  nein  2016-03-23 00:00:00             0       88361
19                  nein  2016-04-01 00:00:00             0       49565
20                  nein  2016-04-01 00:00:00             0       75365
21                  nein  2016-03-27 00:00:00             0       68309
22                  nein  2016-03-23 00:00:00             0       49716
23                  nein  2016-03-12 00:00:00             0        9526
24                    ja  2016-03-13 00:00:00             0       35390
25                    ja  2016-03-18 00:00:00             0       73765
26                  nein  2016-03-10 00:00:00             0       31139
27                  nein  2016-03-07 00:00:00             0       12621
28                  nein  2016-03-09 00:00:00             0       87471
29                  nein  2016-03-08 00:00:00             0       86199
...                  ...                  ...           ...         ...
371498               NaN  2016-03-11 00:00:00             0       65936
371499              nein  2016-03-08 00:00:00             0       24850
371500              nein  2016-03-21 00:00:00             0       38470
371501              nein  2016-03-26 00:00:00             0       34320
371502              nein  2016-04-01 00:00:00             0       34414
371503              nein  2016-03-31 00:00:00             0       90439
371504               NaN  2016-03-07 00:00:00             0       61169
371505                ja  2016-04-03 00:00:00             0       58730
371506              nein  2016-03-20 00:00:00             0        1217
371507               NaN  2016-03-16 00:00:00             0       56472
371508              nein  2016-04-02 00:00:00             0       23820
371509              nein  2016-03-11 00:00:00             0       87700
371510              nein  2016-03-05 00:00:00             0       60437
371511              nein  2016-03-31 00:00:00             0        4275
371512                ja  2016-03-25 00:00:00             0       90473
371513              nein  2016-03-21 00:00:00             0       45896
371514               NaN  2016-04-04 00:00:00             0       88477
371515               NaN  2016-03-09 00:00:00             0       18246
371516              nein  2016-04-04 00:00:00             0       48653
371517              nein  2016-03-28 00:00:00             0       75223
371518              nein  2016-04-02 00:00:00             0       81825
371519              nein  2016-03-09 00:00:00             0       51371
371520                ja  2016-03-19 00:00:00             0       96465
371521              nein  2016-03-27 00:00:00             0       26624

In [5]:
#now printing the coulmn name and the shape of the dataset 
print(df.columns ,df.shape)

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object') (371528, 20)

In [6]:
#printing the information of the salers
print(df.seller.value_counts())

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [7]:
#removing the details of the saler who has only three cars
df[df.seller != 'gewerblich']

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450Â€_VB,privat,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÃœV_3.2018,privat,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [8]:
# we have all the details of saller are same so we have to remove the column 
df=df.drop('seller',1)

In [9]:
#print all the different sellers
print(df.offerType.value_counts())

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [10]:
#remove the Offer Type having only 12 listings
df[df.offerType != 'Gesuch']

,dateCrawled,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450Â€_VB,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÃœV_3.2018,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [11]:
#now all the offers are same so we can get rid of this column
df=df.drop('offerType',1)

In [12]:
# Cars having power less than 50ps and above 900ps are little bit suspious so we have to get ride of thes column 
print(df.shape)

(371528, 18)

In [13]:
df = df[(df.powerPS > 50) & (df.powerPS < 900)]
print(df.shape)

(319709, 18)

In [14]:
#simlarly, filtering our the cars having registeration years not in the mentioned range
print(df.shape)

(319709, 18)

In [15]:
df = df[(df.yearOfRegistration >= 1950) & (df.yearOfRegistration < 2017)]
print(df.shape)

(309171, 18)

In [16]:
#the details which are irrelivent should be removed 
df.drop(['name','abtest', 'dateCrawled', 'nrOfPictures', 'lastSeen',
         'postalCode', 'dateCreated'], axis='columns', inplace=True)

In [17]:
print(df.shape)

(309171, 11)

In [18]:
#final data that we have now
print(df.shape)

(309171, 11)

In [19]:
#dropping the duplicates from the dataframe and stroing it in a new df.
#here all rows having same value in all the mentioned columns will be deleted and by default,
#only first occurance of anysuch row is kept
new_df = df.copy()
new_df = new_df.drop_duplicates(['price','vehicleType','yearOfRegistration'
                         ,'gearbox','powerPS','model','kilometer','monthOfRegistration','fuelType'
                         ,'notRepairedDamage'])

In [20]:
#after removing duplicates
print(new_df.shape)

(285145, 11)

In [21]:
#As the dataset contained some german words for many features, cahnging them to english
new_df.gearbox.replace(('manuell', 'automatik'), ('manual','automatic'), inplace=True)
new_df.fuelType.replace(('benzin','andere','elektro'),('petrol','others','electric'),inplace=True)
new_df.vehicleType.replace(('kleinwagen', 'cabrio','kombi','andere'),
                           ('small car','convertible','combination','others'),inplace=True)
new_df.notRepairedDamage.replace(('ja','nein'),('Yes','No'),inplace=True)

In [22]:
#### Removing the outliers
new_df = new_df[(new_df.price >= 100) & (new_df.price <= 150000)]

In [23]:
#Filling NaN values for columns whose data might not be there with the information provider,
#which might lead to some variance but our model
#but we will still be able to give some estimate to the user
new_df['notRepairedDamage'].fillna(value='not-declared', inplace=True)
new_df['fuelType'].fillna(value='not-declared', inplace=True)
new_df['gearbox'].fillna(value='not-declared', inplace=True)
new_df['vehicleType'].fillna(value='not-declared', inplace=True)
new_df['model'].fillna(value='not-declared', inplace=True)

In [24]:
#can save the csv for future purpose. 
new_df.to_csv("autos_preprocessed.csv")

In [25]:
#Columns which contain categorical values, which we'll need to convert via label encoding
labels = ['gearbox', 'notRepairedDamage', 'model', 'brand', 'fuelType', 'vehicleType']

In [26]:
#looping over the labels to do the label encoding for all at once and 
#saving the LABEL ENCODING FILES
mapper = {}
for i in labels:
    mapper[i] = LabelEncoder()
    mapper[i].fit(new_df[i])
    tr = mapper[i].transform(new_df[i])
    np.save(str('classes'+i+'.npy'), mapper[i].classes_)
    print(i,":",mapper[i])
    new_df.loc[:, i + '_labels'] = pd.Series(tr, index=new_df.index)

gearbox : LabelEncoder()
notRepairedDamage : LabelEncoder()
model : LabelEncoder()
brand : LabelEncoder()
fuelType : LabelEncoder()
vehicleType : LabelEncoder()

In [27]:
#Final data to be put in a new dataframe called "LABELED",
labeled = new_df[ ['price'
                        ,'yearOfRegistration'
                        ,'powerPS'
                        ,'kilometer'
                        ,'monthOfRegistration'
                        ] 
                    + [x+"_labels" for x in labels]]

print(labeled.columns)

Index(['price', 'yearOfRegistration', 'powerPS', 'kilometer',
       'monthOfRegistration', 'gearbox_labels', 'notRepairedDamage_labels',
       'model_labels', 'brand_labels', 'fuelType_labels',
       'vehicleType_labels'],
      dtype='object')

In [28]:
#Storing price in Y and rest of the data in X
Y = labeled.iloc[:,0].values
X = labeled.iloc[:,1:].values

In [29]:
#need to reshape the Y values
Y = Y.reshape(-1,1)

In [30]:
from sklearn.model_selection import cross_val_score, train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state = 3)

In [31]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
regressor = RandomForestRegressor(n_estimators=1000,max_depth=10,random_state=34)

In [32]:
#fitting the model
regressor.fit(X_train, np.ravel(Y_train,order='C'))

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=34, verbose=0, warm_start=False)

In [33]:
#predicting the values fo test test
y_pred = regressor.predict(X_test)

In [34]:
#for testing on user input values
y_pred1 = regressor.predict([[2011,190,125000,5,1,0,163,1,3,3]])

In [35]:
#predticting price for a user input values
print(y_pred1)

[19559.28944983]

In [36]:
#saving the model for future use.
filename = 'resale_model.sav'
pickle.dump(regressor, open(filename, 'wb'))